# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_check_chordal <- function(g, capU, p, chordal, order) {
    .Call(`_BVS4GCR_cpp_check_chordal`, g, capU, p, chordal, order)
}

cpp_find_clique_containing_zo <- function(a, cliques) {
    .Call(`_BVS4GCR_cpp_find_clique_containing_zo`, a, cliques)
}

find_and_replace <- function(A, find_val = 3.0, replace_val = 1.5) {
    .Call(`_BVS4GCR_find_and_replace`, A, find_val, replace_val)
}

cpp_reachability_graph <- function(g) {
    .Call(`_BVS4GCR_cpp_reachability_graph`, g)
}

cpp_ripcliques_to_jtree_zo <- function(print, cliques, jtree, p, num_cliques) {
    .Call(`_BVS4GCR_cpp_ripcliques_to_jtree_zo`, print, cliques, jtree, p, num_cliques)
}

cpp_setdiff_zo <- function(a, b) {
    .Call(`_BVS4GCR_cpp_setdiff_zo`, a, b)
}

cpp_union_zo <- function(b) {
    .Call(`_BVS4GCR_cpp_union_zo`, b)
}

